- hosts: localhost
  become: yes
  tasks:
   - name: Installation of OMS agent
     shell: ./omsagent-1.3.1-15.universal.x64.sh --force --upgrade  -w  "$(grep OMS_WORKSPACEID /etc/omscreds | awk -F":" '{ print $2}')" -s "$(grep OMS_WORKSPACEKEY /etc/omscreds | awk -F":" '{ print $2}')" 
   - name: reload systemd
     command: systemctl daemon-reload
   - name: enabling oms config
     shell: /opt/microsoft/omsconfig/Scripts/OMS_MetaConfigHelper.py –enable
